export type ISODateString = string

export interface PersistedEntity {
  id: string
  createdAt: ISODateString
  updatedAt: ISODateString
}

export interface SyncableEntity extends PersistedEntity {
  deletedAt: ISODateString | null
  syncVersion: number
}

export type BillType = 'utility' | 'operating_cost' | 'annual_statement'
export type BalanceType = 'credit' | 'payment_due' | 'none'
export type OCRStatus = 'pending' | 'processing' | 'needs_review' | 'verified' | 'failed' | 'not_started'
export type CategoryType = 'cost' | 'contract' | 'both' | 'income'
export type CostSource = 'bill' | 'contract' | 'manual' | 'import'
export type CancellationUnit = 'days' | 'weeks' | 'months' | 'years'
export type ReminderType = 'cancellation' | 'contract_end' | 'custom'
export type ReminderStatus = 'pending' | 'sent' | 'dismissed'
export type DocumentType = 'bill' | 'contract' | 'waste' | 'other'
export type WasteCategory = 'residual' | 'organic' | 'paper' | 'recycling' | 'bulky' | 'other'

export interface User extends SyncableEntity {
  displayName: string
  email?: string
}

export interface Property extends SyncableEntity {
  userId: string
  name: string
  address?: string
}

export interface Bill extends SyncableEntity {
  userId: string
  propertyId?: string
  type: BillType
  year: number
  periodStart?: ISODateString
  periodEnd?: ISODateString
  totalAmount: number
  /** true when totalAmount is a deliberately confirmed amount (e.g. from a
   * reviewed OCR import) that may legitimately differ from the sum of this
   * Bill's items; false/undefined means totalAmount is simply derived from
   * that sum, as for a normal manually entered Bill. */
  totalAmountConfirmed?: boolean
  advancePayments: number
  balance: number
  balanceType: BalanceType
  documentId?: string
}

export interface BillItem extends SyncableEntity {
  billId: string
  categoryId?: string
  description: string
  amount: number
  confidence: number
  sourceText?: string
  manuallyVerified: boolean
}

export interface Category extends PersistedEntity {
  name: string
  icon: string
  type: CategoryType
  /** Id of the category this one is grouped under in finance views
   * (e.g. Heizung → Wohnen). Absent = the category is its own group. */
  group?: string
}

export interface CostEntry extends SyncableEntity {
  userId: string
  categoryId: string
  amount: number
  date: ISODateString
  period?: string
  source: CostSource
  contractId?: string
  billId?: string
  notes?: string
}

export interface WasteCost extends SyncableEntity {
  userId: string
  year: number
  category: WasteCategory
  amount: number
  notes?: string
  documentId?: string
}

export interface Contract extends SyncableEntity {
  userId: string
  categoryId: string
  provider: string
  tariff?: string
  contractNumber?: string
  monthlyCost: number
  yearlyCost?: number
  startDate: ISODateString
  endDate?: ISODateString
  cancellationPeriodValue?: number
  cancellationPeriodUnit?: CancellationUnit
  calculatedCancellationDate?: ISODateString
  autoRenewal: boolean
  reminderEnabled: boolean
  documentId?: string
  notes?: string
}

export interface Reminder extends SyncableEntity {
  userId: string
  contractId?: string
  reminderDate: ISODateString
  type: ReminderType
  status: ReminderStatus
  /** How many days before the target date (e.g. a contract's
   * calculatedCancellationDate) this reminder fires - only set for
   * type: 'cancellation' reminders generated by generateContractReminders.
   * Identifies which of the (90/30/7/1-day, configurable) standard
   * intervals a reminder belongs to, so regenerating reminders after a
   * contract change can update the right existing record in place instead
   * of matching on the reminderDate alone (which changes when the
   * contract's cancellation date changes). Optional and additive - no
   * IndexedDB schema/version change needed, existing records without it
   * simply have it undefined. */
  offsetDays?: number
}

export interface Document extends SyncableEntity {
  userId: string
  type: DocumentType
  filename: string
  mimeType: string
  size: number
  storagePath: string
  ocrStatus: OCRStatus
  ocrText?: string
  checksum?: string
}

export interface SyncQueueItem extends PersistedEntity {
  entityType: EntityType
  entityId: string
  operation: 'upsert' | 'delete'
  queuedAt: ISODateString
  attempts: number
}

export type EntityType = 'users' | 'properties' | 'bills' | 'billItems' | 'categories' | 'costEntries' | 'wasteCosts' | 'contracts' | 'reminders' | 'documents'

export type EntityMap = {
  users: User
  properties: Property
  bills: Bill
  billItems: BillItem
  categories: Category
  costEntries: CostEntry
  wasteCosts: WasteCost
  contracts: Contract
  reminders: Reminder
  documents: Document
}

/*
 * Finanztracker (Phase 14). Local-only by decision (docs/specs/
 * phase-14a-entscheidungen.md): none of these is a SYNC_ENTITY_TYPE, so they
 * carry no deletedAt/syncVersion/userId and are deleted for real - which is
 * also what lets `transactions` keep a unique [accountId, dedupeKey] index.
 */

export type AccountType = 'giro' | 'credit_card'

export interface Account extends PersistedEntity {
  name: string
  bank: 'sparkasse'
  type: AccountType
  last4: string
  /** SHA-256 over identifierSalt + normalized IBAN (giro) or masked card
   * number (credit card). The full IBAN/card number is never stored. */
  identifierHash: string
  identifierSalt: string
}

/** How a booking counts: never two of these at once, so nothing is counted
 * twice. `saving` = moved to an own savings/investment account. */
export type FlowType = 'income' | 'expense' | 'transfer' | 'saving'
export type FlowTypeSource = 'manual' | 'rule' | 'auto'
export type CategorySource = 'manual' | 'rule' | 'contract' | 'bank' | 'none'

export interface Transaction extends PersistedEntity {
  accountId: string
  /** YYYY-MM-DD */
  bookingDate: string
  valueDate?: string
  /** Card purchase date (Belegdatum). */
  purchaseDate?: string
  /** Signed, in euros: negative = money leaves the account. */
  amount: number
  currency: string
  counterpartyName: string
  counterpartyIban?: string
  purpose: string
  bookingText: string
  creditorId?: string
  mandateReference?: string
  endToEndReference?: string
  categoryId?: string
  categorySource: CategorySource
  bankCategory?: string
  flowType: FlowType
  flowTypeSource: FlowTypeSource
  /** The other half of a giro ↔ credit card settlement pair. */
  transferPairId?: string
  /** Only set when the export carries a real foreign currency. */
  originalAmount?: number
  originalCurrency?: string
  exchangeRate?: number
  isReversal?: boolean
  /** Card merchant category code (ISO 18245) from the card export. */
  merchantCategoryCode?: string
  /** May point to a contract that no longer exists (contracts sync, bookings
   * do not) - readers must treat a missing contract as "unlinked". */
  contractId?: string
  importBatchId: string
  dedupeKey: string
  notes?: string
}

export interface ImportBatchCounts {
  total: number
  new: number
  duplicates: number
  skippedPending: number
}

export interface ImportBatch extends PersistedEntity {
  accountId: string
  filename: string
  fileChecksum: string
  importedAt: ISODateString
  /** YYYY-MM-DD */
  periodFrom: string
  periodTo: string
  counts: ImportBatchCounts
}

export type CategoryRuleField = 'counterpartyName' | 'purpose' | 'creditorId' | 'counterpartyIban'

export interface CategoryRule extends PersistedEntity {
  field: CategoryRuleField
  matchType: 'contains' | 'equals'
  pattern: string
  /** At least one of categoryId / flowType is set. */
  categoryId?: string
  flowType?: FlowType
  priority: number
  createdFrom: 'manual' | 'seed'
}

export interface SavingsGoal extends PersistedEntity {
  monthlyTarget: number
}
